### ISSUE TITLE
Issues with "Tab for URLs with Title and Icon" command

### ISSUE THREAD

**Issue by richlux** [hluk/copyq-commands#1]
I'm using a CopyQ command from the repository to get the URL with Title and Icon (https://github.com/hluk/copyq-commands/blob/master/Automatic/tab-for-urls-with-title-and-icon.ini) and it gets the Title and the URL perfectly, but often it does not get the Icon.  For example, it doesn't get an icon for http://www.woot.com or http://www.bgr.com. Second, when it does get an Icon, there is always an extra grey square in front of it. Is there a way to remove the grey square? See the attached screenshot for examples.

![image](https://user-images.githubusercontent.com/25157703/40123665-bb5f5936-58f4-11e8-9a66-2995694a414e.png)

Thanks,
Rich

**Comment by hluk** [comment]
Looks like there are some HTTP redirects that cannot be handled by CopyQ.

Though retrieve the favicon, it's possible to use https://s2.googleusercontent.com/s2/favicons?domain_url=http://www.bgr.com/.

```ini
[Command]
Automatic=true
Command="
    copyq:
    var tabName = '&url'
    
    function lower(data) {
      return str(data).toLowerCase()
    }
    
    function isHtml(reply) {
      var headers = reply.headers
      for (var i in headers) {
        var header = headers[i]
        if (lower(header[0]) === 'content-type')
           return lower(header[1]).indexOf(mimeHtml) === 0
      }
      return false
    }
    
    function grep(content, re) {
      return content ? (re.exec(content) || [])[1] : ''
    }
    
    function getTitle(content) {
      var title = grep(content, /<title[^>]*>([^<]*)<\\/title>/i)
      return title ? title.trim() : ''
    }
    
    function getFavicon(url) {
      var faviconUrl = 'https://s2.googleusercontent.com/s2/favicons?domain_url='
           + encodeURIComponent(url)
      return networkGet(faviconUrl).data
    }
    
    tab(tabName)
    
    var url = str(input()).trim()
    
    // URL already added? (Just check the top of the list.)
    if (url === str(read(0)))
      abort()
    
    // Fetch HTML.
    var reply = networkGet(url)
    var title = ''
    if (isHtml(reply)) {
      var content = str(reply.data)
      title = getTitle(content)
    }
    
    var icon = getFavicon(url)
    write(
      mimeText, url,
      mimeItemNotes, title || '',
      'application/x-copyq-item-icon', icon
    )"
Icon=\xf0c1
Input=text/plain
Match=^https?://
Name=Tab for URLs with Title and Icon
```

**Comment by hluk** [comment]
Here is updated command that uses an HTTP API even to retrieve the title:

```ini
[Command]
Automatic=true
Command="
    copyq:
    var tabName = '&url'
    
    function callApi(apiBaseUrl, url) {
      var apiUrl = apiBaseUrl + encodeURIComponent(url)
      return networkGet(apiUrl).data
    }
    
    tab(tabName)
    
    var url = str(input()).trim()
    
    // URL already added? (Just check the top of the list.)
    if (url === str(read(0)))
      abort()
    
    var title = callApi('https://textance.herokuapp.com/rest/title/', url)
    var icon = callApi('https://s2.googleusercontent.com/s2/favicons?domain_url=', url)
    
    write(
      mimeText, url,
      mimeItemNotes, title || '',
      'application/x-copyq-item-icon', icon
    )"
Icon=\xf0c1
Input=text/plain
Match=^https?://
Name=Tab for URLs with Title and Icon
```

**Comment by richlux** [comment]
Thanks!  That seems to work better (although a little slower). Do you know what the grey box before the Icon is and is there a way to get rid of it?

Rich

**Comment by hluk** [comment]
> Do you know what the grey box before the Icon is and is there a way to get rid of it?

That grey box indicates an item notes.

You can create HTML instead:

```ini
[Command]
Automatic=true
Command="
    copyq:
    var tabName = '&url'
    
    function callApi(apiBaseUrl, url) {
      var apiUrl = apiBaseUrl + encodeURIComponent(url)
      return networkGet(apiUrl).data
    }
    
    tab(tabName)
    
    var url = str(input()).trim()
    
    // URL already added? (Just check the top of the list.)
    if (url === str(read(0)))
      abort()
    
    var title = callApi('https://textance.herokuapp.com/rest/title/', url)
    var icon = callApi('https://s2.googleusercontent.com/s2/favicons?domain_url=', url)
    var html = '<img src=\"data:image/png;base64,' + toBase64(icon) + '\" /> '
             + '<a href=\"' + url + '\">' + escapeHtml(title) + '</a>'
    
    write(
      mimeText, url,
      mimeHtml, html
    )"
Icon=\xf0c1
Input=text/plain
Match=^https?://
Name=Tab for URLs with Title and Icon
```

**Comment by hluk** [comment]
> Unfortunately, when I copy a URL, I get a "SyntaxError: Parse error" Exception.

Strange, works for me. Can you try again? There should be more details in the log (F12 shortcut).

**Comment by richlux** [comment]
Ok, I deleted the command and re-added it.  Must have been a funky character in the code somewhere.  Thanks for the quick response on this.

Rich

**Comment by richlux** [comment]
Sorry for re-opening this, but I have a few other questions.  First, I noticed that the URL is no longer showing, just the title.  Second, if you copy a site that does not exist or is password protected, the whole HTML error message (from the S2 Google call) is displayed in CopyQ (see below with hover text).  I understand that the calls will fail, but can CopyQ not show all the error text?

![image](https://user-images.githubusercontent.com/25157703/45175959-9d9c7c80-b1dc-11e8-9099-5ff41edda4a1.png)

Thanks again,
Rich

**Comment by hluk** [comment]
Fix:

```ini
[Command]
Automatic=true
Command="
    copyq:
    var tabName = '&url'
    
    function callApi(apiBaseUrl, url) {
      var apiUrl = apiBaseUrl + encodeURIComponent(url)
      var response = networkGet(apiUrl)
      var result = response.data
      if (response.error || response.status >= 300)
        return ''
      return result
    }
    
    tab(tabName)
    
    var url = str(input()).trim()
    
    // URL already added? (Just check the top of the list.)
    if (url === str(read(0)))
      abort()
    
    var title = callApi('https://textance.herokuapp.com/rest/title/', url)
    if (!title)
      title = url
    var icon = callApi('https://s2.googleusercontent.com/s2/favicons?domain_url=', url)
    var html = (icon ? '<img src=\"data:image/png;base64,' + toBase64(icon) + '\" /> ' : '')
             + '<a href=\"' + url + '\">' + escapeHtml(title) + '</a>'
    
    write(
      mimeText, url,
      mimeHtml, html
    )"
Icon=\xf0c1
Input=text/plain
Match=^https?://
Name=Tab for URLs with Title and Icon
```

**Comment by hluk** [comment]
I also updated [the command in repo](https://github.com/hluk/copyq-commands/blob/master/Automatic/tab-for-urls-with-title-and-icon.ini) so it allows HTTP redirects. It's bit better but the regex to find the icon URL still fails sometimes.

**Comment by richlux** [comment]
Thanks so much.  Is there a way to debug these command scripts? I'm trying to create a combination of the two commands (the original one you just updated and the new one with the callApi commands), but I'm struggling.  I really like the way the original scripts gets the Title for sites that require authentication (the new script can't since it's pulling it from an external source) and getting the icon is faster. I'm trying to combine the two scripts so it only calls the external callApi commands if it can't get the information the other way.  What I'm doing isn't working and it's difficult to debug it without being able to see what the variables contain at different steps of the code.

Thanks again,
Rich

**Comment by fyanchev** [comment]
Hi hluk, 

is there a way to pip this to automatically shorten url - did not find such functionality either shorten the url with shortcut or automatically by just selecting and copying it?

Second question - using above script - not getting any errors, the url tab is there - but there are only links (but getting them duplicated) no title and icon. Any advice?

![image](https://user-images.githubusercontent.com/29201536/57096961-21344c00-6d1f-11e9-8347-a24087146e92.png)
![image](https://user-images.githubusercontent.com/29201536/57097113-85efa680-6d1f-11e9-8417-7187380d8b53.png)

**Comment by hluk** [comment]
Use the command from the copyq-commands repository: https://github.com/hluk/copyq-commands/tree/master/Automatic#tab-for-urls-with-title-and-icon

The repo contains more up to date commands.

The command may still fail to retrieve title or icon from the HTML in some cases. I started using [Show Window Title](https://github.com/hluk/copyq-commands/tree/master/Automatic#show-window-title) instead (no icon though).

To shorten the URL, ideally if you have a utility that can do this and pass the URL through it, e.g.:

```js
result = execute('url-shortener', url)
url = str(result.stdout)
```

**Comment by fyanchev** [comment]
hi thank you, will look for a URL shortening utility, would be great if you could recommend any working good with CopyQ. 

Dummy question - getting error Warning [2019-05-03 12:01:13.310] <Server-17388>: Failed to set global shortcut "Meta+Alt+T" for command "Paste Current Time".

On modern keyboards, where can I find the Meta Key - did not find any advice - is this the Windows key or other key?

**Comment by hluk** [comment]
> Dummy question - getting error Warning [2019-05-03 12:01:13.310] : Failed to set global shortcut "Meta+Alt+T" for command "Paste Current Time".

Try to set the shortcut again. Maybe the key names changed or the shortcut is already set for other command.

> On modern keyboards, where can I find the Meta Key - did not find any advice - is this the Windows key or other key?

Yes, "Meta" is usually the Windows key.
