### ISSUE TITLE
CopyQ v8 and v9 crash often

### ISSUE THREAD

**Issue by kayanco** [hluk/copyq-commands#100]
Hi,

Version 7 of CopyQ is stable for me. But when I tested v8 and v9, both would often crash on Windows 11.

The way I would find out is that CopyQ wouldn't appear Shortcut press. Checking the system tray, CopyQ isn't present. So I re-launch again. Then the same thing after some time (maybe few hours).

Same behavior on v8 and v8. OS is Windows 11. Version 7 didn't have this issue.

**Comment by hluk** [comment]
This repository is only for CopyQ commands. Better open an issue in https://github.com/hluk/copyq. But there is a little for me to work with - you will also have to include at least **application log** (F12 shortcut from the app).
