### ISSUE TITLE
Why do Notes (application/x-copyq-item-notes) not appear when copying from the edit field?

### ISSUE THREAD

**Issue by iG8R** [hluk/copyq-commands#102]
I use the following command:

```
[Command]
Name=Add URL label
Command="
    copyq:
    removeData('text/x-moz-url-priv')
    var url = input()
    url.chop(1)
    setData(mimeItemNotes, url)"
Input=text/x-moz-url-priv
Automatic=true
Icon=
```

Why do Notes (application/x-copyq-item-notes) not appear when copying from the edit field?

![image](https://github.com/hluk/copyq-commands/assets/11407417/e5ca3ad4-c0db-4923-a363-4f573223b39b)

**Comment by hluk** [comment]
It is because, unfortunately, the required format `text/x-moz-url-priv` is not available when copying from text fields. Not sure why Firefox does not provide it.
