### ISSUE TITLE
Global shortcuts don't work with ZSA keyboard firmware.

### ISSUE THREAD

**Issue by imzoc** [hluk/copyq-commands#104]
Hi!

I had a copyq command that used the global shortcut `Alt+D`. The global command doesn't work with my Moonlander keyboard running ZSA's firmware. I have tried setting the global shortcut to unshared keys on my first layer and it still doesn't work. The command still works when I run it from the dropdown menu, it's just the global shortcut that doesn't work.

I have found a workaround. I create a bash script, write 'copyq eval " " ' and then paste whatever I had written in the copyq command in between the double quotation marks. Then I create a GNOME shortcut that runs the bash script. GNOME seems to detect the keystrokes, and the bash script does exactly the same thing.

However, I would like to at least put it on your radar that the global shortcuts don't work for some reason with my Moonlander.

For reference, here is my hardware and software:
* Thinkpad P14s Gen 2 (with Ryzen 5650U processor)
* Ubuntu 22.04.4 LTS
* GNOME 42.9 with Wayland
* Moonlander Mk. 2
* Wally keyboard firmware flasher V2.1.3

**Comment by hluk** [comment]
Unfortunately, global shortcuts do not work under Wayland. See: https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland

A workaround is to install [Wayland Support](https://github.com/hluk/copyq-commands/tree/master/Scripts#wayland-support) command (mentioned in the link above) and assign a shortcut in the desktop environment to `copyq triggerGlobalShortcut "COMMAND_NAME"` to launch a global shortcut command defined in CopyQ.
