### ISSUE TITLE
Paste as Plain Text Command Displays 'Text Copied' Alert on Every Paste

### ISSUE THREAD

**Issue by pa-0** [hluk/copyq-commands#106]
I'm currently using the following to paste plain text:

```javascript
//[Command]
//Name=Paste clipboard as plain text
//Command="
    copyq: 
    var text = clipboard()
    copy(text)
    copySelection(text)
    paste()"
//IsGlobalShortcut=true
//Icon=
//GlobalShortcut=ctrl+shift+v
//InternalId=copyq_global_paste_clipboard_plain
```
Is there a way to prevent this command from displaying a 'copied' alert everytime I _paste_ something?

**Comment by hluk** [comment]
This is a feature in CopyQ itself. See: [FAQ: How to enable or disable displaying notification when clipboard changes?](https://copyq.readthedocs.io/en/latest/faq.html#how-to-enable-or-disable-displaying-notification-when-clipboard-changes)
