### ISSUE TITLE
trying to make command to replace single quote with two single quotes and vice versa

### ISSUE THREAD

**Issue by gooddadmike** [hluk/copyq-commands#14]
I'm doing a lot of database word where I'm passing some dynamic sql. 
``` sql
CASE WHEN [t].[VALUE] = 'Foo' THEN NULL ELSE 'Bar' END
```
and I often need to reverse it from `''` to `'` as well. 

I have tried it this way
```qt
copyq:
function modifyText(text)
{
  // TODO: Modify text here!
  return text.replace("'", "''")
}

if (!copy())
  abort()

var text = str(clipboard())
var newText = modifyText(text)
if (text == newText)
  abort();

copy(newText)
paste()
```
and it only replaces the very first `'` with `''`. It never gets them both. Any help appreciated.

**Comment by garulovilla** [comment]
You need to use a regex `text.replace(/'/g, "''")`. If you don't use a regex only the first occurrence is replaced. Yo can check the documentation in [String.prototype.replace()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace).

**Comment by gooddadmike** [comment]
This solved me up. Thanks!
