### ISSUE TITLE
Copy nth command 

### ISSUE THREAD

**Issue by fabiodocit123** [hluk/copyq-commands#16]
Please when i press shortcuts to copy item 0 or item 1 command for example 
i need ever open copyQ window to change clipboard value ?
is possible for only press shortcuts and change clipboard value ?

**Comment by hluk** [comment]
Which shourtcut do you mean and where? What do you mean by "clipboard value"?

**Comment by fabiodocit123** [comment]
sorry clipboard "content"

**Comment by hluk** [comment]
I still don't understand the questions. Is this related to some command? (Issues related to the application are in [CopyQ repository](https://github.com/hluk/CopyQ/issues).)

If you want to edit current clipboard content there is predefined command "Edit clipboard" in CopyQ.

**Comment by fabiodocit123** [comment]
that command

**Comment by fabiodocit123** [comment]
copyq:
var shortcut = str(data("application/x-copyq-shortcut"))
var number = shortcut ? shortcut.replace(/^\D+/g, '') : currentItem();
selectItems(number)
copy("application/x-copyq-item", pack(getItem(number)))

to activate this command i need open copy q window right ? 
this work with global shorcut ? 
example > copy the content 1 and content 2 
and i need use the content 1 three times and content 2 three times in altenate moments (for example)
i can change this values with global shorcuts ? for i dont need open copyq software window

**Comment by hluk** [comment]
> this work with global shorcut ?

Did you try to enable "Global Shortcut" for the command in Command dialog? It should be possible to use both.

![image](https://user-images.githubusercontent.com/38054/63106705-ba603900-bf83-11e9-8746-c78676430cfe.png)
