### ISSUE TITLE
clear all tabs and clipboard

### ISSUE THREAD

**Issue by samkhan1** [hluk/copyq-commands#17]
I just wanted a simple clipboard manager, how did I end up with an IDE called CopyQ??? :joy:

I am really not able to figure out whether the syntax of copyq is pearl, js or something custom. Unfortunately I'm not good at either. 

Well anywas, could you please paste a code snippet here, as a reply, for clearning (deleting or removing) all tabs, items and contents with in-menu button and global shortcut. 

Thank you.

**Comment by hluk** [comment]
Scripting language of CopyQ is basically JavaScript ([Qt Script](https://doc.qt.io/qt-5/qtscript-index.html) to be more specific).

More info about clearing tabs can be found in CopyQ issues:
- Clear Clipboar Tab command: https://github.com/hluk/CopyQ/issues/1031#issuecomment-434036500
- Disable storing items completely for a tab: https://github.com/hluk/CopyQ/issues/1063
