### ISSUE TITLE
errors running to-title-case.ini

### ISSUE THREAD

**Issue by jhooly** [hluk/copyq-commands#2]
i've cut-and-paste the command text into Copyq, all seemed good. i get the following error every time:
![screenshot from 2018-05-20 21-22-01](https://user-images.githubusercontent.com/38855773/40283325-50784e10-5c74-11e8-8c11-a11c025a80bc.png)

(apologies for using a screengrab, "insert code" didn't seem to work as expected.)

**Comment by hluk** [comment]
Look like copying from active window fails. The command tried to sends <kbd>Ctrl</kbd>+<kbd>C</kbd> shortcut to active window and waits for clipboard to change. Unfortunately, this can fail for some apps and in some environments.

**Comment by jhooly** [comment]
okay, good to know. thank you for the reply.
