### ISSUE TITLE
 Error: TLS initialization failed

### ISSUE THREAD

**Issue by neoOpus** [hluk/copyq-commands#22]
Note [2020-06-08 02:39:07.057] <Client-8888>:    --- backtrace ---
Note [2020-06-08 02:39:07.057] <Client-8888>:    importCommandsFromUrl(url = 'https://github.com/hluk/copyq-commands/blob/master/Automatic/big-data-tab.ini') at “...”:23
Note [2020-06-08 02:39:07.057] <Client-8888>:    <eval>() at “...”:31
Note [2020-06-08 02:39:07.057] <Client-8888>:    <eval>() at “...”:4
Note [2020-06-08 02:39:07.057] <Client-8888>:    --- end backtrace ---
Note [2020-06-08 02:40:11.855] <Client-24360>: ScriptError: Exception in command: Failed to fetch commands.
Note [2020-06-08 02:40:11.855] <Client-24360>:    Status code: undefined
Note [2020-06-08 02:40:11.855] <Client-24360>:    Error: TLS initialization failed

**Comment by neoOpus** [comment]
OK I found a fix myself

The format of the import command must be as highlighted in the screenshot.

![image](https://user-images.githubusercontent.com/1388336/84000718-2c4ea800-a933-11ea-802c-1025b2ca7c41.png)

**Comment by neoOpus** [comment]
This is still not working... the import dialogue windows shows up but the import command does nothing and there is no log... I tried different combinations but nothing helps, so I thing something is broken QCopy.

**Comment by hluk** [comment]
I think it's related to this: https://github.com/hluk/CopyQ/issues/1177

**Comment by hluk** [comment]
Fixed in [hluk/CopyQ#1177](https://github.com/hluk/CopyQ/issues/1177).
