### ISSUE TITLE
Adding hotkey to ignore any copied text when held down

### ISSUE THREAD

**Issue by wahost070** [hluk/copyq-commands#40]
I was hoping you could help with a solution for the following script you wrote:

[https://github.com/hluk/copyq-commands/blob/master/Global/copy-a-secret.ini](url)

I'm using BitWarden and I frequently use the "copy password to clipboard" button on my password manager, rendering the copy secret hotkey ineffective. Would there be a way to set a hotkey that I would hold, and then click the "copy password to clipboard" button so the password would be ignored?

Any help would be appreciated!

**Comment by hluk** [comment]
How about [Copy a Secret If a Modifier Held](https://github.com/hluk/copyq-commands/tree/master/Automatic#copy-a-secret-if-a-modifier-held) command? (I've only just created it.)

**Comment by wahost070** [comment]
Perfect, works like a charm! Thanks for your help 🙂
