### ISSUE TITLE
command List all tabs?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/copyq-commands#41]
Hi.
I do not find the option to list all tabs and jump to a certain one per click.
Is there such script, command?
Where could i post a wish? :)
thx

**Comment by hluk** [comment]
List tabs: `copyq tab`

Show specific tab: `copyq show TAB`

**Comment by Clemens-Ratte-Polle** [comment]
ok, these are for the Command Line, but i meant commands :)
I have many tabs and so many of them are "hidden", so i want to see them all and select one by a shortcut.
Is there a "forum" where CQ users would help each other? :)
thx

**Comment by hluk** [comment]
> I have many tabs and so many of them are "hidden", so i want to see them all and select one by a shortcut.

Here is a command that shows a dialog with the tab list:

```ini
[Command]
Command="
    copyq:
    var tabs = tab().sort()
    var index = dialog(
        '.height', 600,
        '.list:Tab', tabs)
    if (index !== undefined)
        show(tabs[index])"
Icon=\xf022
InMenu=true
Name=Tabs
Shortcut=ctrl+shift+s
```

BTW, you can also use `&` in tab name for a shortcut (see https://copyq.readthedocs.io/en/latest/tabs-and-items.html#tabs) or Ctrl+0..9.

**Comment by sl5net** [comment]
> Show specific tab: `copyq show TAB`
and it creates new tabs

**Comment by sl5net** [comment]
`Error: execve: No such file or directory` using kUbuntu

**Comment by Clemens-Ratte-Polle** [comment]
THANKS VERY MUCH!
Great command :)

And how without sorting?
var tabs = tab() 
without: .sort() ?

**Comment by sl5net** [comment]
![image](https://user-images.githubusercontent.com/5634759/126521317-c596f2b5-e81c-45eb-acff-31c3b5425ccf.png)

**Comment by garulovilla** [comment]
You need to add it in the command section: File > Commands.

![image](https://user-images.githubusercontent.com/4468146/126548590-f6e65439-f871-4e0e-b062-0c39fe95d9fa.png)

And add a new command:

![image](https://user-images.githubusercontent.com/4468146/126548658-3c300dcf-2105-4be5-b836-f0dba27db024.png)

Check de FAQ section in [How to load shared commands and share them?](https://copyq.readthedocs.io/en/latest/faq.html#faq-share-commands)

**Comment by sl5net** [comment]
> You need to add it in the command section: File > Commands.
> 
> ![image](https://user-images.githubusercontent.com/4468146/126548590-f6e65439-f871-4e0e-b062-0c39fe95d9fa.png)
> 
> And add a new command:
> 
> ![image](https://user-images.githubusercontent.com/4468146/126548658-3c300dcf-2105-4be5-b836-f0dba27db024.png)
> 
> Check de FAQ section in [How to load shared commands and share them?](https://copyq.readthedocs.io/en/latest/faq.html#faq-share-commands)

F6 > Add > New command > Show Advanced (is then enabled next time) > Name it + Paste Script > Save it

works. my first copyQ-Script

**Comment by sl5net** [comment]
thanks works, but is it possible to get the search also as feature-rich as the search in the other tabs?
BTW i have created a tab tabs ( https://stackoverflow.com/a/68480690/2891692 ). but of course my tab tabs don't enable me to switch fast to the tab selected. just enables to copy and find a existing tab (needs refreshed manually by sh-script)

**Comment by sl5net** [comment]
workaround thats works very good for me in Linux:
```
copyq removetab tabs ; ./tabs.sh ; copyq tab > tabs.sh ; sort -buo ./tabs.sh ./tabs.sh ; sed -i 's/.*/copyq tab pana3 add "&"/' tabs.sh ;  chmod +x ./tabs.sh ; ./tabs.sh
```

**Comment by Clemens-Ratte-Polle** [comment]
hi.
To click in the list and jump to a specific tab would be fine :)
