### ISSUE TITLE
symfony-console-autocomplete using copyQ

### ISSUE THREAD

**Issue by sl5net** [hluk/copyq-commands#43]
I would like to give you this one Liner, my first copyQ oneLiner.

This will help completion build symfony consolne commands. 

if you use a tab named symfonyBinConsole backup it first !!!

```
clear; copyq removetab symfonyBinConsole; copyq show symfonyBinConsole; rm ./symfonyBinConsole2copyQ.sh;  ~/symfony/example/bin/console > symfonyBinConsole2copyQ.sh; sed -ri 's/\s*([^ ]+)(.*)/copyq tab symfonyBinConsole add "\1 # \2"/' symfonyBinConsole2copyQ.sh ; chmod +x ./symfonyBinConsole2copyQ.sh ; ./symfonyBinConsole2copyQ.sh 

```

BTW: First i tried https://github.com/bamarni/symfony-console-autocomplete but not works for me.

**Comment by sl5net** [comment]
maybe you cant/want add this in a collection of useful scripts.

**Comment by hluk** [comment]
This is perhaps for very specific use case - I do not know nor use symfony console.

Feel free to create a pull request to add any useful commands (with description in a README file).
