### ISSUE TITLE
Ubuntu cant 'Store Window Title'

### ISSUE THREAD

**Issue by sl5net** [hluk/copyq-commands#44]
https://github.com/hluk/copyq-commands/blob/6307052e3667017a71acbac166f397060df6287c/Automatic/show-window-title.ini#L1

no errors but

i checked items and clipboard. => no changes.

**Comment by hluk** [comment]
This is probably because getting window title is not supported on Wayland (see https://github.com/hluk/CopyQ/issues/27).
