### ISSUE TITLE
Notification for Copied Commands grabbing incorrect Content/Windows Match rules

### ISSUE THREAD

**Issue by Lockszmith-GH** [hluk/copyq-commands#45]
This is about https://github.com/hluk/copyq-commands/blob/master/Automatic/import-commands-after-copied.ini

When importing a command by manually copy-pasting - everything works.
When importing a command via the (awesome) utility script (link above), the Advanced / Match Items / Content and Window fields are populated with the values below:
```
/\/(?:)\//
```

This causes (most) commands to not function properly until properly removing the bad content.

If the script **includes** matching, then the escaping is off, and for any `\` a `\\` is populated.

**Comment by hluk** [comment]
Fixing. Thanks a lot for the report!

**Comment by Lockszmith-GH** [comment]
Thanks A LOT for making this AWESOME tool 😄
