### ISSUE TITLE
Separate tabs for long items

### ISSUE THREAD

**Issue by pesader** [hluk/copyq-commands#46]
First of all, thanks for developing CopyQ! By now, it saved me countless of hours of work, all the while looking incredibly pretty (the UI and UX are top notch).

In my daily usage I often find myself copying a lot of lines at once, such that a single item fills up the entire CopyQ window as seen in the image below.

![image](https://user-images.githubusercontent.com/65264536/128772133-cf21b3f6-5637-42e4-b2e6-9754828644cf.png)

How would I go about creating an Automatic script to move these long items to a separate tab (perhaps named `&long`)? I took a look at the Scrpting API documentation but haven't gotten any ideas from it. So far, I have a hunch that a modified version of the [Big Data Script](https://github.com/hluk/copyq-commands/blob/ee93b281f426d2b2e2b8166f6c10a613b38bc3bf/Automatic/big-data-tab.ini) may do the trick.

Thanks in advance!

**Comment by hluk** [comment]
Maybe use a simpler version of the "Big Data Tab" automated command:

```ini
[Command]
Automatic=true
Command="
    copyq:
    var tabName = '&long'
    var minBytes = 10*1000
    if (data(mimeText).size() >= minBytes) {
        setData(mimeOutputTab, tabName)
    }"
Icon=\xf039
Name=Long Text Tab
```
