### ISSUE TITLE
[Feature Request] Save current selected image as a file.

### ISSUE THREAD

**Issue by zw963** [hluk/copyq-commands#52]
![image](https://user-images.githubusercontent.com/549126/148898196-181df3f0-6636-43ca-8e3f-a798b8ae3611.png)

Is the exists a command which can save current selected images (maybe copy from a screenshot programmer) into a image(e.g. png) file?

Thank you!

**Comment by garulovilla** [comment]
Hi! Have you tried this command [save-item-clipboard-to-file.ini](https://github.com/hluk/copyq-commands/blob/master/Application/save-item-clipboard-to-file.ini)?

**Comment by zw963** [comment]
When click following button to select a folder to save current file.

![image](https://user-images.githubusercontent.com/549126/149060765-a6922dce-d85d-4be7-8540-5d36aa3e2e2b.png)

The open folder dialog is shadowed by copyq dialog.

![image](https://user-images.githubusercontent.com/549126/149060235-129eeacc-de97-4863-9f2d-554e21130b50.png)

I don't know if this is a issue, anyway, if we can improve, that will best.

**Comment by hluk** [comment]
Looks like a bug in Qt or native file dialogs. I assume the main window has always-on-top flag set but somehow it is not propagated to the file dialog.
