### ISSUE TITLE
Global/snippets.ini Doesn't Work With Index 0

### ISSUE THREAD

**Issue by styper** [hluk/copyq-commands#56]
Found a bug on snippets.ini where when you select the first snippet it doesn't pastes and throws no error.

Looking into the source it's the "|| abort()" on line 64, it activates the abort because the zero index evaluates to false.

Since dialog() returns "undefined" when cancelling the dialog, the snippet var should be evaluated as:

if (typeof snippet === "undefined")
    abort()

**Comment by hluk** [comment]
Fixed. Thanks for the report and details!
