### ISSUE TITLE
It seems `shift-insert` in wayland-support only work for `primary`?

### ISSUE THREAD

**Issue by YinAqu** [hluk/copyq-commands#69]
In my environments, copyq paste selected item to `clipboard` rather than `primary` after `enter`, which results `shift-insert` not work, but `ctrl-shift-v` works. Is there something wrong config in my copyq? Appreciate for your work!

**Comment by hluk** [comment]
You would need to change the shortcut send via `ydotool`:

https://github.com/hluk/copyq-commands/blob/286b8c931ef44da0823e4bf47c6878962a5f4d6c/Scripts/wayland-support.ini#L78

For Ctrl+Shift+V it would be:

```js
sendShortcut('29:1', '42:1', '47:1', '47:0', '42:0', '29:0')
```
