### ISSUE TITLE
CopyQ: Command Search&Replace?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/copyq-commands#74]
Hi.
Top app! :)
What about a command to search and replace specific text in an opened and edited item ?
Or globally for all items in the actual tab or all tabs?
thx :)

**Comment by hluk** [comment]
I've created [Search & Replace](https://github.com/hluk/copyq-commands/tree/master/Application#search--replace) command (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).

**Comment by hluk** [comment]
What are the formats in the item? You can see the formats by selecting the item and selecting "Show Content..." from context menu (F4 shortcut).

It's possible that there is no "text/plain" format and the URL is stored under "text/uri-list".

**Comment by ChristopheC13** [comment]
Hi,

The format is text/plain (see with "Show Content..." from context menu (F4 shortcut)).

I think it's the \\ or \ or # that's the problem in the url

A solution to improve the commande of Application/search-and-replace.ini to meet this need ?

Thanks in advance

**Comment by hluk** [comment]
> I think it's the \ or \ or # that's the problem in the url

I tested the command without encountering any problems. I don't see any `\` in your example input.
