### ISSUE TITLE
Copy-to-tab makes clipboard selection to copy everything

### ISSUE THREAD

**Issue by gerardbosch** [hluk/copyq-commands#78]
Hi,

I'm using this command https://github.com/hluk/copyq-commands/blob/master/Automatic/move-images-to-other-tab.ini
to copy (not move) images to the "Images" tab.

I don't know how to programmatically do it, so I installed the command and in "Advanced" tab, I set the "Copy to tab: clipboard":

![image](https://github.com/hluk/copyq-commands/assets/30733556/f555705f-31f7-41f9-87ff-d02081c267be)

It did the job (although I'd like to know how to alter the command for no manual setup)

### The issue

* After doing that, every text selection from the mouse gets copied to the main "clipboard" tab 😳.

I tried removing the command and starting over again and same result. When I disable the command the mouse selection works fine.

CopyQ Clipboard Manager 7.1.0
Qt: 6.5.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 23.04
X11

**N.B.** I did exactly the same with this command to **copy** URLs in a tab and the mouse works just fine!
https://github.com/hluk/copyq-commands/blob/master/Automatic/tab-for-urls-with-title-and-icon.ini

**Comment by hluk** [comment]
I think you need to set Format field in Advanced tab to some `image/*` format.

**Comment by gerardbosch** [comment]
Thanks for your answer!

I tried `image/*` but nothing was copied. Then I used `image/png` and seems to work! Now images are present in both `clipboard` tab and `Images` 🙂 and the mouse selection is not copied anywhere! ✅

![image](https://github.com/hluk/copyq-commands/assets/30733556/4dc680c9-bcbc-48ce-993c-7e42bfe993c1)
