### ISSUE TITLE
feature request: apply Display Commands to the tray menu items

### ISSUE THREAD

**Issue by jkatnik** [hluk/copyq-commands#79]
Hello,

is it possible to apply Display Command to items in the tray menu?
I'd like to mask all items starting with some prefix.
E.g. items starting with 'S$' should be displayed in the tray menu as 'Masked Password'.

The below Command works as expected in the main CopyQ window, but it doesn't in the tray menu.
```
copyq:
const textData = str(data(mimeText));
const passwordPrefix = 'S$';

if (textData.startsWith(passwordPrefix)) {
  setData('text/plain', 'Masked Password');
}
```

![image](https://github.com/hluk/copyq-commands/assets/7869474/bc64e9bd-9144-4148-a324-4ca40bb998c3)

Cheers
  Jarek

**Comment by hluk** [comment]
Thanks for the suggestion. This will be possible in the next CopyQ release (#2566).
